//
//  CoachService.swift
//  FinTrack — the money coach's model backend.
//
//  Ported from `askCoach()` in FinTrack.dc.html (L722-761). The prototype called the
//  hosted `window.claude.complete`; the shipping app talks to a LOCAL Ollama instance on
//  the host's loopback (Info.plist sets NSAllowsLocalNetworking so the simulator can reach
//  127.0.0.1). The system prompt, the snapshot it embeds and the offline text are the
//  prototype's, character for character.
//

import Foundation
import Observation

// MARK: - Chat message

/// One turn of the conversation. The greeting bubble is generated by the view and is
/// deliberately NOT stored here — the prototype prepends it to `this.state.chat` at render
/// time, so it never becomes history the model sees.
struct ChatMessage: Identifiable, Hashable, Sendable {

    enum Role: Sendable, Hashable {
        case user
        case coach
    }

    let id: UUID
    let role: Role
    let text: String

    init(role: Role, text: String) {
        self.id = UUID()
        self.role = role
        self.text = text
    }
}

// MARK: - Service

/// Owns the conversation and the one in-flight request.
///
/// A single shared instance survives tab switches: `RootView` rebuilds `CoachView` from a
/// `switch` every time the tab changes, so view-local state would drop the history the
/// prototype keeps in app state.
@MainActor
@Observable
final class CoachService {

    static let shared = CoachService()

    /// The stored conversation, oldest first. Excludes the generated greeting.
    private(set) var messages: [ChatMessage] = []

    /// True from the moment a question is sent until its reply (or fallback) lands.
    private(set) var isThinking = false

    /// The Ollama tag resolved on first use, reused for the rest of the session.
    @ObservationIgnored fileprivate var resolvedModel: String?
    @ObservationIgnored private var didWarmUp = false

    @ObservationIgnored private var inFlight: Task<Void, Never>?

    init() {}

    /// `askCoach(text)` — appends the user turn, flips the thinking bubble on, and awaits
    /// the model. Whitespace-only input and re-entry while thinking are both no-ops,
    /// exactly as the prototype's `sendChat` guard and `if (this.state.thinking) return`.
    /// Called when the Coach tab appears. Loads the model in the background so the first
    /// message does not have to wait for a cold read off disk. Never blocks the UI and
    /// never surfaces an error — if Ollama is not running, the reply path falls back.
    func warmUpIfNeeded() {
        guard !didWarmUp else { return }
        didWarmUp = true
        let known = resolvedModel
        Task.detached(priority: .utility) {
            let name = await CoachWire.warmUp(knownModel: known)
            if let name { await MainActor.run { CoachService.shared.resolvedModel = name } }
        }
    }

    func send(_ text: String, store: AppStore) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !isThinking else { return }

        // The history the model sees is everything BEFORE this turn.
        let history = messages.map { CoachWire.Message(role: $0.role == .user ? "user" : "assistant",
                                                       content: $0.text) }
        let system = CoachPrompt.systemPrompt(store: store)
        let fallback = CoachPrompt.offlineFallback(store: store)
        let known = resolvedModel

        messages.append(ChatMessage(role: .user, text: trimmed))
        isThinking = true

        let outgoing = history + [CoachWire.Message(role: "user", content: trimmed)]

        // The class is @MainActor, so this Task starts on the main actor and every `await`
        // inside `CoachWire` hops to a background executor — the UI never blocks.
        inFlight = Task { [weak self] in
            let outcome = await CoachWire.complete(system: system,
                                                   messages: outgoing,
                                                   knownModel: known)
            guard let self, !Task.isCancelled else { return }
            self.finish(outcome, fallback: fallback)
        }
    }

    private func finish(_ outcome: CoachWire.Outcome, fallback: String) {
        let reply: String
        switch outcome {
        case .reply(let text, let model):
            resolvedModel = model
            reply = text
        case .unreachable:
            reply = fallback
        case .failed:
            reply = CoachPrompt.errorReply
        }
        messages.append(ChatMessage(role: .coach, text: reply))
        isThinking = false
        inFlight = nil
    }
}

// MARK: - Prompt construction

/// Everything that has to read the live store. Kept separate so the networking layer stays
/// `nonisolated` and can run entirely off the main actor.
@MainActor
enum CoachPrompt {

    /// `'I couldn\'t reach the model just now — try again in a moment.'`
    static let errorReply = "I couldn't reach the model just now \u{2014} try again in a moment."

    // MARK: System prompt

    static func systemPrompt(store: AppStore) -> String {
        let data = store.data
        let tone = data.coach.tone == .serious ? "precise, professional" : "warm, playful"
        return "You are " + data.coach.name + ", a " + tone +
            " personal finance coach inside the FinTrack app. The user follows a 50/30/20 budget (Needs/Wants/Savings) and an avalanche debt strategy (highest debt first). " +
            "Answer using their real numbers from this snapshot: " + snapshotJSON(store: store) +
            // Guardrail. The prototype's prompt ended at "under 90 words"; this sentence
            // is a deliberate addition. Observed on qwen3.5:9b: handed saved 2400 of
            // target 12000 with remaining 9600, it opened with "You crushed the Travel fund
            // goal!". The model recites supplied figures reliably and characterises them
            // unreliably, so it is told to read status rather than judge progress.
            ". Every figure you need is in the snapshot — use those values and do not " +
            "calculate your own. A milestone is only finished when its status says " +
            "\"complete\"; otherwise say what is still outstanding. " +
            "Be specific and actionable. Plain text only, no markdown, under 90 words."
    }

    /// `JSON.stringify(snapshot)`. The top level is assembled by hand because
    /// `JSONEncoder` serialises a keyed container through a dictionary and emits hash
    /// order, not property-declaration order — so the prototype's object-literal order
    /// would be lost and the prompt would not be byte-stable between builds.
    static func snapshotJSON(store: AppStore) -> String {
        let data = store.data
        let snapshot = Snapshot(
            currency: data.currency,
            accounts: data.accounts.map { .init(name: $0.name, bal: $0.bal) },
            monthlyIncome: data.incomes.map { .init(name: $0.name, amt: $0.amt, type: $0.type.rawValue) },
            loans: data.loans.map {
                .init(name: $0.name,
                      amount: $0.amt,
                      direction: $0.dir == .inbound ? "they owe me" : "I owe them")
            },
            milestones: data.msPersonal.map(Snapshot.Ms.init(milestone:)),
            monthSpendByBucket: .init(needs: data.bucketSpend.needs,
                                      wants: data.bucketSpend.wants,
                                      savings: data.bucketSpend.savings),
            // Omitted entirely when nothing has been recorded, so the model is not handed
            // three zeros to read as a real business picture.
            businessSpendByBucket: data.businessBucketSpend.total > 0
                ? .init(ops: data.businessBucketSpend.ops,
                        growth: data.businessBucketSpend.growth,
                        profit: data.businessBucketSpend.profit)
                : nil,
            recentTransactions: data.days.prefix(2).map { day in
                .init(label: day.label, items: day.items.map {
                    .init(glyph: $0.glyph, tint: $0.tintHex, color: $0.colorHex, title: $0.title,
                          sub: $0.sub, amount: $0.amount, pos: $0.pos, acct: $0.acct)
                })
            }
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]

        // Encode each field on its own, then join in the prototype's order.
        func part<T: Encodable>(_ key: String, _ value: T) -> String? {
            guard let bytes = try? encoder.encode(value),
                  let json = String(data: bytes, encoding: .utf8) else { return nil }
            return "\"\(key)\":\(json)"
        }

        let fields: [String?] = [
            part("currency", snapshot.currency),
            part("accounts", snapshot.accounts),
            part("monthlyIncome", snapshot.monthlyIncome),
            part("loans", snapshot.loans),
            part("milestones", snapshot.milestones),
            part("monthSpendByBucket", snapshot.monthSpendByBucket),
            // nil until a business expense is recorded, and compactMap drops it.
            snapshot.businessSpendByBucket.flatMap { part("businessSpendByBucket", $0) },
            part("recentTransactions", snapshot.recentTransactions),
        ]
        let joined = fields.compactMap { $0 }.joined(separator: ",")
        return joined.isEmpty ? "{}" : "{\(joined)}"
    }

    // MARK: Offline fallback

    /// The prototype's preview-mode answer, verbatim.
    static func offlineFallback(store: AppStore) -> String {
        let data = store.data
        let spend = data.bucketSpend
        // `bs.Needs + bs.Wants + bs.Savings || 1`
        let total = spend.total == 0 ? 1 : spend.total
        let pct = Int(jsRound(spend.wants / total * 100))

        let debt = largest(in: data.loans, direction: .outbound)
        let owed = largest(in: data.loans, direction: .inbound)

        var out = "(Preview mode \u{2014} no model connected here. The real app would answer via a free local model.)\n"
        out += "Quick read: Wants are at \(pct)% of this month's spending"
        if let debt {
            out += "; your avalanche priority is \(debt.name) (\(data.currency) \(store.fmtN(debt.amt)))"
        }
        if let owed {
            out += "; largest amount owed to you is \(owed.name) (\(data.currency) \(store.fmtN(owed.amt)))"
        }
        out += "."
        return out
    }

    /// `filter(...).sort((a, b) => b.amt - a.amt)[0]` under a STABLE sort: the first loan
    /// with a strictly greater amount wins, so ties keep list order.
    private static func largest(in loans: [Loan], direction: LoanDirection) -> Loan? {
        var best: Loan?
        for loan in loans where loan.dir == direction {
            if best == nil || loan.amt > best!.amt { best = loan }
        }
        return best
    }

    // MARK: Snapshot DTOs

    /// Mirrors the prototype's snapshot object exactly — including its key names, which are
    /// not always the Swift model's (`tint`/`color` on a transaction, `color` on a
    /// milestone, capitalised bucket keys).
    private struct Snapshot: Encodable {
        let currency: String
        let accounts: [Acct]
        let monthlyIncome: [Inc]
        let loans: [Ln]
        let milestones: [Ms]
        let monthSpendByBucket: Buckets
        var businessSpendByBucket: BizBuckets?
        let recentTransactions: [Day]

        struct Acct: Encodable { let name: String; let bal: Double }
        struct Inc: Encodable { let name: String; let amt: Double; let type: String }
        struct Ln: Encodable { let name: String; let amount: Double; let direction: String }
        /// `targetDate` and `requiredPerMonth` are omitted entirely for open-ended goals,
        /// so the model is never handed a null to reason about. Without them the coach has
        /// no time dimension for savings at all, which is why "how am I doing on my
        /// milestones" used to get a vague answer.
        /// Every derived figure is sent explicitly rather than left for the model to work
        /// out. Observed failure: given only `targetDate: "Dec 2026"` it had to subtract
        /// dates in its head to say how long was left, and reported the Travel fund as
        /// "12 months" — a figure borrowed from a different milestone. The monthly amounts
        /// in the same reply were correct, because those were handed to it.
        struct Ms: Encodable {
            let name: String
            let saved: Double
            let target: Double
            let color: String
            /// Still to save. Trivial to derive, and therefore trivial to get wrong.
            var remaining: Double?
            var targetDate: String?
            var monthsRemaining: Int?
            var requiredPerMonth: Double?
            /// Present only when the date needs interpreting: "overdue by 12 days" or
            /// "complete". Absent means on the normal path.
            var status: String?

            /// Fills in everything the pace calculation already knows, so the model never
            /// has to derive a date difference.
            init(milestone m: Milestone) {
                name = m.name
                saved = m.saved
                target = m.target
                color = m.colorHex
                remaining = (m.remaining * 100).rounded() / 100
                guard let date = m.targetDate else { return }
                targetDate = FinTrackFormatting.monthYear(date)
                switch m.pace() {
                case .due(let perMonth, let months):
                    monthsRemaining = months
                    requiredPerMonth = (perMonth * 100).rounded() / 100
                case .overdue(let days):
                    status = "overdue by \(days) day\(days == 1 ? "" : "s")"
                case .complete:
                    status = "complete"
                case .noDate:
                    break
                }
            }
        }

        struct BizBuckets: Encodable {
            let ops: Double
            let growth: Double
            let profit: Double
            enum CodingKeys: String, CodingKey {
                case ops = "Ops"
                case growth = "Growth"
                case profit = "Profit"
            }
        }

        struct Buckets: Encodable {
            let needs: Double
            let wants: Double
            let savings: Double
            enum CodingKeys: String, CodingKey {
                case needs = "Needs"
                case wants = "Wants"
                case savings = "Savings"
            }
        }

        struct Tx: Encodable {
            let glyph: String
            let tint: String
            let color: String
            let title: String
            let sub: String
            let amount: String
            let pos: Bool
            let acct: String
        }

        struct Day: Encodable { let label: String; let items: [Tx] }
    }
}

// MARK: - Ollama transport

/// The HTTP layer. Every member is `nonisolated` and every hop runs off the main actor.
enum CoachWire {

    // MARK: Types

    struct Message: Codable, Sendable {
        let role: String
        let content: String
    }

    enum Outcome: Sendable {
        /// A model answered. Carries the tag that answered so it can be cached.
        case reply(String, String)
        /// Ollama is not running / not reachable — show the offline preview text.
        case unreachable
        /// Reached it, but it returned a non-200 or something undecodable.
        case failed
    }

    // MARK: Configuration

    /// Where Ollama lives. `127.0.0.1` is correct in the simulator, which shares the
    /// Mac's loopback — but on a real iPhone loopback is the PHONE, so the coach would
    /// silently fall back to preview mode forever. On device, point this at the Mac's LAN
    /// address via the "Coach server" field in iOS Settings (or the -FTCoachHost argument).
    static var host: String {
        if let override = launchArgumentHost ?? defaultsHost, !override.isEmpty {
            return normalised(override)
        }
        return "http://127.0.0.1:11434"
    }

    /// `-FTCoachHost <url>` — used by tests and by `xcrun devicectl` launches.
    private static var launchArgumentHost: String? {
        let args = ProcessInfo.processInfo.arguments
        guard let i = args.firstIndex(of: "-FTCoachHost"), i + 1 < args.count else { return nil }
        return args[i + 1]
    }

    /// Settable from the iOS Settings app (see Settings.bundle), so a device build can be
    /// pointed at the Mac without touching the app's own designed Settings screen.
    private static var defaultsHost: String? {
        UserDefaults.standard.string(forKey: "coach_host")
    }

    /// Accepts "192.168.1.42", "192.168.1.42:11434" or a full URL.
    private static func normalised(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if !s.contains("://") { s = "http://" + s }
        if URL(string: s)?.port == nil { s += ":11434" }
        return s
    }

    /// Measured against the real coach prompt on a 16GB M5, 3 runs each with `think:false`:
    ///
    ///     model         size    seconds   invented figures   markdown   false verdict
    ///     qwen3.5:4b    3.4GB   6.6-10.6         0/3            0/3          0/3
    ///     qwen3:8b      5.2GB   9.9-11.0         0/3            3/3          1/3
    ///     qwen3.5:9b    6.6GB  14.9-16.0         2/3            0/3          1/3
    ///     gemma3:4b     3.3GB   8.6- 9.4         1/3            0/3          3/3
    ///
    /// 9b was the default and is the worst of the four: slowest, and the only one to
    /// invent figures — it summed the two debts into "15000 SAR total" in a prompt that
    /// says not to calculate. Size did not help, because the task is recitation.
    /// gemma3:4b is excluded from the preference list entirely: it volunteered "you're
    /// crushing it" in 3/3 and derived completion percentages it was told not to, which
    /// is precisely the failure the prompt guardrail exists to prevent.
    static let defaultModel = "qwen3.5:4b"

    /// Descending preference when the default is absent. qwen3:8b is second despite
    /// bolding every reply — `stripMarkdown` handles that, and it was the most accurate
    /// on the pace fields.
    static let modelPreference = [
        "qwen3.5:4b",
        "qwen3:8b",
        "qwen3.5:9b",
        "qwen2.5:7b",
        "llama3.2:3b",
        "llama3.2:1b",
    ]

    private static let session: URLSession = {
        let config = URLSessionConfiguration.ephemeral
        // A cold local model must be read off disk before the first token: qwen3.5:9b is
        // 6.6GB and can take several minutes on first use. 90s turned a working setup into
        // a spurious "couldn't reach the model". The thinking bubble covers the wait.
        config.timeoutIntervalForRequest = 300
        config.timeoutIntervalForResource = 360
        config.waitsForConnectivity = false
        config.allowsCellularAccess = true
        return URLSession(configuration: config)
    }()

    /// Fire-and-forget preload. Ollama loads a model when asked to chat with no messages,
    /// so this pays the cold-start cost while the user is still reading the greeting.
    /// Failures are ignored — this is an optimisation, never a precondition.
    static func warmUp(knownModel: String?) async -> String? {
        let resolved: String?
        if let knownModel { resolved = knownModel } else { resolved = await resolveModel() }
        guard let name = resolved else { return nil }
        guard let url = URL(string: host + "/api/chat") else { return nil }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.timeoutInterval = 300
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let body = ChatRequest(model: name, messages: [], stream: false)
        guard let encoded = try? JSONEncoder().encode(body) else { return nil }
        request.httpBody = encoded
        _ = try? await session.data(for: request)
        return name
    }

    // MARK: Entry point

    static func complete(system: String, messages: [Message], knownModel: String?) async -> Outcome {
        let model: String
        if let knownModel {
            model = knownModel
        } else {
            switch await resolveModel() {
            case .some(let name): model = name
            case .none: return .unreachable
            }
        }

        guard let url = URL(string: host + "/api/chat") else { return .failed }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        // Must match the session budget: a per-request timeoutInterval OVERRIDES
        // configuration.timeoutIntervalForRequest, so leaving 90 here silently defeated it.
        request.timeoutInterval = 300
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        let body = ChatRequest(model: model,
                               messages: [Message(role: "system", content: system)] + messages,
                               stream: false)
        guard let encoded = try? JSONEncoder().encode(body) else { return .failed }
        request.httpBody = encoded

        do {
            let (data, response) = try await session.data(for: request)
            guard let http = response as? HTTPURLResponse, http.statusCode == 200 else { return .failed }
            guard let decoded = try? JSONDecoder().decode(ChatResponse.self, from: data) else { return .failed }
            let text = stripMarkdown(stripThinking(decoded.message.content))
            guard !text.isEmpty else { return .failed }
            return .reply(text, model)
        } catch let error as URLError where error.code == .timedOut {
            // The tags probe already proved the daemon is up, so a timeout here means a
            // slow (usually cold-loading) model, not an absent one.
            return .failed
        } catch {
            // A transport error on loopback means Ollama is not listening.
            return .unreachable
        }
    }

    // MARK: Model resolution

    /// `GET /api/tags`. Returns nil only when the daemon is unreachable; an unexpected but
    /// answered payload falls back to the default tag and lets `/api/chat` be the judge.
    static func resolveModel() async -> String? {
        guard let url = URL(string: host + "/api/tags") else { return defaultModel }
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 10

        let data: Data
        do {
            let (payload, response) = try await session.data(for: request)
            guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
                return defaultModel
            }
            data = payload
        } catch {
            return nil
        }

        guard let tags = try? JSONDecoder().decode(TagsResponse.self, from: data) else {
            return defaultModel
        }
        let installed = tags.models.map(\.name)
        guard !installed.isEmpty else { return defaultModel }

        for candidate in modelPreference {
            if let match = installed.first(where: { $0 == candidate })
                ?? installed.first(where: { $0.hasPrefix(candidate) }) {
                return match
            }
        }
        return installed[0]
    }

    // MARK: Reasoning-block stripping

    /// Local reasoning models (qwen3.x, deepseek-r1, …) wrap their scratchpad in
    /// `<think>…</think>`. Remove complete blocks, then any stray half of a block.
    static func stripThinking(_ raw: String) -> String {
        var out = raw
        if let regex = try? NSRegularExpression(pattern: "<think>[\\s\\S]*?</think>",
                                                options: [.caseInsensitive]) {
            out = regex.stringByReplacingMatches(in: out,
                                                 options: [],
                                                 range: NSRange(out.startIndex..., in: out),
                                                 withTemplate: "")
        }
        // A close with no open: everything before it was reasoning.
        if let close = out.range(of: "</think>", options: [.caseInsensitive, .backwards]) {
            out = String(out[close.upperBound...])
        }
        // An open with no close: everything after it is reasoning.
        if let open = out.range(of: "<think>", options: [.caseInsensitive]) {
            out = String(out[..<open.lowerBound])
        }
        return out.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// The prompt asks for plain text, and most models comply — but qwen3:8b bolded every
    /// reply in 3/3 measured runs, and the coach bubble renders its string literally, so
    /// the user would read `**Travel fund**` with the asterisks. Stripping is cheaper than
    /// rendering Markdown: the coach's replies are one short paragraph, and emphasis it was
    /// asked not to use carries no meaning worth preserving.
    ///
    /// Deliberately conservative. Single `_` is left alone (it appears inside words far more
    /// often than as emphasis), and `*` is only unwrapped as a matched pair around
    /// non-space content, so an asterisk used as a literal character survives.
    static func stripMarkdown(_ raw: String) -> String {
        var out = raw
        let rules: [(String, String)] = [
            ("\\*\\*(.+?)\\*\\*", "$1"),          // **bold**
            ("__(.+?)__", "$1"),                  // __bold__
            ("\\*(?=\\S)(.+?)(?<=\\S)\\*", "$1"), // *italic*, never across spaces
            ("`(.+?)`", "$1"),                    // `code`
            ("\\[(.+?)\\]\\((?:.+?)\\)", "$1"),   // [text](url) -> text
            ("(?m)^\\s{0,3}#{1,6}\\s+", ""),      // # heading
            ("(?m)^\\s{0,3}[-*+]\\s+", ""),       // - bullet
        ]
        for (pattern, template) in rules {
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            out = regex.stringByReplacingMatches(in: out,
                                                 options: [],
                                                 range: NSRange(out.startIndex..., in: out),
                                                 withTemplate: template)
        }
        return out.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: Wire DTOs

    private struct ChatRequest: Encodable {
        let model: String
        let messages: [Message]
        let stream: Bool
        /// Hold the model in memory between turns so only the first message of a session
        /// pays the multi-second (or multi-minute) load cost.
        var keep_alive: String = "30m"
        /// Qwen 3.5 and friends are REASONING models: left alone they spend most of their
        /// output budget on hidden thinking. Measured on qwen3.5:9b with this exact prompt,
        /// a reply cost ~4 minutes and ~2,000 tokens with thinking on, and 21s / 107 tokens
        /// with it off — same answer quality, since the coach wants a short plain-text
        /// verdict rather than a derivation. Ollama accepts the flag for non-thinking
        /// models too (verified against llama3.2:1b), so it is safe to send unconditionally.
        var think: Bool = false
    }

    private struct ChatResponse: Decodable {
        struct Payload: Decodable { let content: String }
        let message: Payload
    }

    private struct TagsResponse: Decodable {
        struct Tag: Decodable { let name: String }
        let models: [Tag]
    }
}
